# Generated by Django 5.0.3 on 2025-03-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments about this alert', null=True),
        ),
    ]
